# Generated by Django 6.0.3 on 2026-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="event_asset"),
        ),
    ]
