# Generated by Django 6.0.3 on 2026-05-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_event_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="asset",
            field=models.ImageField(
                blank=True, null=True, upload_to="participant_asset"
            ),
        ),
    ]
